"""Initial migration

Revision ID: 3939db5132a1
Revises: 
Create Date: 2025-01-12 21:25:02.506862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3939db5132a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroes_id'), 'heroes', ['id'], unique=False)
    op.create_index(op.f('ix_heroes_name'), 'heroes', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('sites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('stockable_metal', sa.Float(), nullable=True),
    sa.Column('available_metal', sa.Float(), nullable=True),
    sa.Column('stockable_crystals', sa.Float(), nullable=True),
    sa.Column('available_crystals', sa.Float(), nullable=True),
    sa.Column('stockable_deuterium', sa.Float(), nullable=True),
    sa.Column('available_deuterium', sa.Float(), nullable=True),
    sa.Column('beans_factory_level', sa.Integer(), nullable=True),
    sa.Column('mana_extraction_plan_level', sa.Integer(), nullable=True),
    sa.Column('gotcha_temple_level', sa.Integer(), nullable=True),
    sa.Column('cannon_meat_farm_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('user_hero_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hero_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('settings', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hero_id', name='uix_user_hero')
    )
    op.create_index(op.f('ix_user_hero_relationships_id'), 'user_hero_relationships', ['id'], unique=False)
    op.create_table('armies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('starting_site_id', sa.String(), nullable=False),
    sa.Column('destination_site_id', sa.String(), nullable=True),
    sa.Column('departure_time', sa.BigInteger(), nullable=True),
    sa.Column('starlight_sprinter', sa.Integer(), nullable=True),
    sa.Column('nebula_noodle_hauler', sa.Integer(), nullable=True),
    sa.Column('astro_idol_cruiser', sa.Integer(), nullable=True),
    sa.Column('photon_feather', sa.Integer(), nullable=True),
    sa.Column('waifu_wing_destroyer', sa.Integer(), nullable=True),
    sa.Column('pudding_mecha', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['starting_site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_armies_id'), 'armies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_armies_id'), table_name='armies')
    op.drop_table('armies')
    op.drop_index(op.f('ix_user_hero_relationships_id'), table_name='user_hero_relationships')
    op.drop_table('user_hero_relationships')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_heroes_name'), table_name='heroes')
    op.drop_index(op.f('ix_heroes_id'), table_name='heroes')
    op.drop_table('heroes')
    # ### end Alembic commands ###
